main: com.swiftpenguin.CrazyLoggerSP.CrazyLoggerSP
name: ABMCCrazyLogger
version: 2.0
author: MasterGabeMOD & Cobwebster
depend: [CrazyCrates]

commands:
  crazylogger:
     description: lookup cmd
     usuage: /<command>

permissions:
    crazylogger.lookup:
        description: Allows lookup
        default: op
    crazylogger.exempt:
        description: Exempt from logging
        default: op